version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - mongodb:/data/db
  
  node:
    depends_on:
      - mongodb
    build:
      dockerfile: Dockerfile
      context: "./node"
    restart: always
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - /app/node_modules
      - ./node:/data/node
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true

  react:
    build:
      dockerfile: Dockerfile
      context: ./react
    restart: always
    volumes:
      - /app/node_modules
      - ./react:/data/react
    stdin_open: true